# Generated by Django 4.2.1 on 2023-05-31 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=15)),
                ("data_registro", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=15)),
                ("data_registro", models.DateField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contatos",
                        to="register.cliente",
                    ),
                ),
            ],
        ),
    ]
